In [1]:
import numpy as np

### 1.5.2 넘파이 배열 생성하기
---------

In [2]:
x = np.array([1.0, 2.0, 3.0])

In [3]:
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

### 1.5.3 넘파이의 산술 연산
------------

In [5]:
y = np.array([2.0, 4.0, 6.0])

In [6]:
x + y

array([3., 6., 9.])

In [7]:
x * y

array([ 2.,  8., 18.])

In [8]:
x/y

array([0.5, 0.5, 0.5])

In [9]:
x/2.0

array([0.5, 1. , 1.5])

### 1.5.4 넘파이의 N차원 배열
-----

In [10]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [11]:
a.shape

(2, 2)

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([[3,0],[0,6]])

In [14]:
a + b

array([[ 4,  2],
       [ 3, 10]])

In [15]:
a * b

array([[ 3,  0],
       [ 0, 24]])

### 벡터? 행렬?

----------
- 수학에서 1차원 배열을 [벡터]
- 2차원 배열을 [행렬]
- 벡터와 행렬을 일반화한 것을 [텐서]
- 3차원 이상의 배열을 [다차원 배열]

### 1.5.5 브로드캐스트
-----

2x2 행렬 a에 스칼라값 10을 곱했습니다.  
10이라는 스클라값이 2x2 행렬로 확대된 후 연산이 이뤄집니다.  
이 똑똑한 기능을 브로드캐스트 라고 합니다.

In [16]:
print(a)

[[1 2]
 [3 4]]


In [17]:
a * 10

array([[10, 20],
       [30, 40]])

-----
- 형상이 다른 배열끼리의 연산

In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])
a * b

array([[10, 40],
       [30, 80]])

### 1.5.6 원소 접근
----

In [21]:
x = np.array([[51,55],[14,19],[0,4]])
print(x)

[[51 55]
 [14 19]
 [ 0  4]]


In [22]:
x[0]

array([51, 55])

In [23]:
x[0][1]

55

In [24]:
for row in x:
    print(row)

[51 55]
[14 19]
[0 4]


In [25]:
x = x.flatten()   #x를 1차원 배열로 변환(평탄화)

In [26]:
print(x)

[51 55 14 19  0  4]


In [27]:
x[np.array([0,2,4])]  # 인덱스가 0,2,4인 원소 얻기

array([51, 14,  0])

In [42]:
x > 15

array([ True,  True, False,  True, False, False])

In [43]:
x[x>15]

array([51, 55, 19])

- 넘파이의 주된 처리는 C와 C++로 구현했기 때문에 성능을 해치지 않으면서 파이썬의 편리한 문법을 사용할 수 있다.